### ISSUE TITLE
Some commands are case sensitive

### ISSUE THREAD

**Issue by TZilba** [IstalriSkolir/Lakea-Stream-Assistant#292]
!addquote for example will not work if you write !Addquote

![Screenshot_20240917_202403_Twitch](https://github.com/user-attachments/assets/8c256f96-3497-4c4e-ae8d-67fb8db6c812)

Subtract 1 hour from time stamps for British time.

**Comment by IstalriSkolir** [comment]
This is a quick fix that should be implemented next time work is done on the stream assistant. Adding to the ToDo list on the project board.
