### ISSUE TITLE
Investigate Data Communication Methods Between Lakea And Woodland

### ISSUE THREAD

**Issue by IstalriSkolir** [IstalriSkolir/Lakea-Stream-Assistant#7]
Research and prototype ways to have Lakea and the woodland exchange data for triggering events

**Comment by JohnWolfson** [comment]
Investigate the following library, its available on both Nuget and the Unity Asset store which would make implementing easier

https://netly.docs.kezero.com/overview/netly

**Comment by JohnWolfson** [comment]
Discussions with other Devs has found some other potential methods:

- Named Pipes can allow applications to send data to each other when on the same machine
- TCP calls can be made though are not the easiest to implement or work with
- GRPC will serialise data into binary data optimising bandwidth and may be a suitable end goal, however, it requires more set up and not a method I currently know anything about

**Comment by JohnWolfson** [comment]
A potentially useful resource for configuring TCP messages

https://learn.microsoft.com/en-us/dotnet/fundamentals/networking/sockets/socket-services

**Comment by JohnWolfson** [comment]
A working prototype of a websocket server in .NET has been developed with python scripts being able to connect. The same library (WebSocketSharp) can be used in Unity to create a client that can connect to the server. With a working websocket prototype developed, this will likely be the chosen method moving forward.

https://medium.com/unity-nodejs/websocket-client-server-unity-nodejs-e33604c6a006

**Comment by IstalriSkolir** [comment]
With the investigation complete, this issue can be closed.
